# Generated by Django 3.0.6 on 2020-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200516_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='kind',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Transfer', 'Transfer')], max_length=8),
        ),
    ]
