# Generated by Django 3.0.6 on 2020-05-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200516_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BankAccount'),
        ),
    ]
