# Generated by Django 3.0.6 on 2020-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_operation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
