# Generated by Django 3.0.6 on 2020-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200517_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
